leftnav:
- identifier: 63c5cb0c-f90f-7199-0522-1a99178e67cf
  name: Syllabus
  url: /pages/syllabus/
  weight: 10
- identifier: 3807e520-fab5-0938-3a1e-d3ce2fb8a836
  name: More on Grading Scale and Course Policies
  parent: 63c5cb0c-f90f-7199-0522-1a99178e67cf
  url: /pages/syllabus/more-on-grading-scale-and-course-policies
  weight: 20
- identifier: 64897f6f-e8c9-c5ad-31c1-8b04a2b18491
  name: Readings & Listening
  url: /pages/readings-listening
  weight: 30
- identifier: bee8ef0a-23b6-359b-9791-d3c3f59c2018
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 7530842c-e0a0-043c-107f-4e25ef92a9fc
  name: music21 Tools
  url: /pages/music21-tools
  weight: 50
